fix: added auto deployement

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -218,3 +218,18 @@ jobs:
           labels: ${{ steps.meta.outputs.labels }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
+  deploy:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Deploy LunaStore
+        env:
+          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$DEPLOY_URL")
+          
+          if [ "$response" -eq 200 ]; then
+            echo "Deployment successfully triggered!"
+          else
+            echo "Deployment failed with HTTP status code: $response"
+            exit 1
+          fi
